#!/bin/bash

for serial in USB0 USB1 USB2 USB3; do
    grep -q 'pl2303' /sys/class/tty/tty${serial}/device/uevent 2>/dev/null && dev=/dev/tty${serial}
done

hex=`find build/ -type f -name *.hex`
hex_num=`echo "${hex}" | wc -l`

if [ -n "${dev}" -a "${hex_num}" = 1 ]; then
    avrdude -C/etc/avrdude.conf -patmega328p -cstk500v2 -P${dev} -e -Ulfuse:w:0xff:m -Uhfuse:w:0xde:m -Uefuse:w:0x05:m -Ulock:w:0x3F:m
    avrdude -C/etc/avrdude.conf -patmega328p -cstk500v2 -P${dev} -V -D -Uflash:w:${hex}:i
else
    echo 'programmer or hex file not found'
fi
