
# Board settings.
#BOARD = atmega328

MON_SPEED = 9600

# Where to find header files and libraries.
#INC_DIRS = ./inc
LIB_DIRS = ../../libs/SoftwareSerial ../../libs/IRremote ../../libs/Sensirion ../../libs/ds3231 /usr/share/arduino-0022/libraries/Wire/ /usr/share/arduino-0022/libraries/Wire/utility/

include ../Makefile.master

