
# Board settings.
#BOARD = atmega328

MON_SPEED = 9600

# Where to find header files and libraries.
#INC_DIRS = ./inc
LIB_DIRS = ../../libs/IRremote ../../libs/Sensirion ../../libs/ds3231 ../../libs/SdFat ../../libs/max6675 /usr/share/arduino-100/libraries/Wire/ /usr/share/arduino-100/libraries/Wire/utility/ /usr/share/arduino-100/libraries/SPI/ /usr/share/arduino-100/libraries/SoftwareSerial

include ../Makefile.master

