
# Board settings.
#BOARD = atmega328
#MON_SPEED = 9600

# Where to find header files and libraries.
#INC_DIRS = ./inc
LIB_DIRS = ../../libs/IRremote ../../libs/Sensirion ../../libs/ds3231 ../../libs/SdFat ../../libs/max6675 ../../libs/bmp085 ../../libs/intertechno /local/arduino-100/libraries/Wire /local/arduino-100/libraries/Wire/utility /local/arduino-100/libraries/SPI/

include Makefile.master

